feat: finshed container3 #17
behappywendy/transparent_text_effect pull request #20
Opened 2022-04-25 08:36 UTC by yoshuu

mission completed

2022-04-25 09:41 UTC, cc5324 approved these changes
Okay, approved!

2022-04-25 12:30 UTC, cc5324 requested changes
背景不要直接用 gif 檔，請改用 animation 讓背景移動吧～ 甘溫～ (sorry~ 
補充: 因為有新增的 merge 紀錄，記得要再抓最新版的 main 下來，辛苦了

2022-04-27 05:32 UTC, cc5324 requested changes
嗚嗚，main 有新 merge 阿傑和 Rex 的 code，再麻煩你 pull 新的內容後，解衝突後重新丟上來，謝謝～

2022-04-27 07:47 UTC, yoshuu commented
@cc5324 @behappywendy @southAndy

2022-04-28 00:38 UTC, yoshuu commented
@cc5324 @behappywendy @southAndy ，以解完衝突丟上，請查收。

2022-04-28 02:13 UTC, cc5324 approved these changes

2022-04-28 03:07 UTC, closed without merging